apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: floci-az-acr-registry:5000/acrplatformsre/worker:e20a47b6d9386fde269aae250999d72da00ea842
          imagePullPolicy: IfNotPresent
          ports:
            - name: metrics
              containerPort: 9090
              protocol: TCP
          env:
            - name: METRICS_PORT
              value: "9090"
            - name: SERVICEBUS_URL
              value: "amqp://servicebus.jobs.svc.cluster.local:5672"
            - name: SERVICEBUS_QUEUE
              value: "jobs"
            - name: PGHOST
              value: "postgres.jobs.svc.cluster.local"
            - name: PGPORT
              value: "5432"
            - name: PGSSLMODE
              value: "disable"
            - name: BLOB_URL
              value: "http://blob-storage:4577/devstoreaccount1"
            - name: BLOB_CONTAINER
              value: "job-results"
          envFrom:
            - secretRef:
                name: postgres-credentials
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 100m
              memory: 64Mi
