apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: jobs-api
        metrics_path: /metrics
        static_configs:
          - targets:
              - jobs-api.jobs.svc.cluster.local:8080

      - job_name: worker
        metrics_path: /metrics
        static_configs:
          - targets:
              - worker-metrics.jobs.svc.cluster.local:9090
