apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobs-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobs-api
  template:
    metadata:
      labels:
        app: jobs-api
    spec:
      containers:
        - name: jobs-api
          image: floci-az-acr-registry:5000/acrplatformsre/jobs-api:v2
          imagePullPolicy: IfNotPresent
          env:
            - name: SERVICEBUS_URL
              value: "amqp://servicebus:5672"
            - name: SERVICEBUS_QUEUE
              value: "jobs"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 100m
              memory: 64Mi
