apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: servicebus
  namespace: jobs
  labels:
    kubernetes.io/service-name: servicebus
addressType: IPv4
ports:
  - name: amqp
    protocol: TCP
    port: 5673
endpoints:
  - addresses:
      - "172.18.0.1"
